### ISSUE TITLE
icon not clickable

### ISSUE THREAD

**Issue by F3der1co** [ConstructFund/constructfund.github.io#1]
![image](https://github.com/ConstructFund/constructfund.github.io/assets/89512047/60e011d3-da83-46bc-8545-5031e9491d7d)
button clickable but icon isn't, made me click and nothing happend multiple times already xD

**Comment by skymen** [comment]
Has been fixed by [Armaldio](https://github.com/ConstructFund/constructfund.github.io/pull/4)
